# Generated by Django 6.0.5 on 2026-07-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='college',
        ),
        migrations.AlterModelTable(
            name='principal',
            table='principal',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
