# Generated by Django 6.0.5 on 2026-07-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_college_table_alter_principal_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='principal',
            old_name='college_id',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject_code',
            new_name='subject',
        ),
    ]
