# Generated by Django 6.0.5 on 2026-07-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_rename_college_id_principal_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='subject_code',
        ),
    ]
