# Generated by Django 6.1.1 on 2026-09-18 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_rename_subject_teacher_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.college'),
        ),
    ]
