# Generated by Django 6.1.1 on 2026-09-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_teacher_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.college'),
        ),
    ]
