# Generated by Django 6.0.5 on 2026-06-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('publisher', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
