# Generated by Django 6.0.5 on 2026-06-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
