# Generated by Django 6.0.5 on 2026-07-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.BooleanField(default=True),
        ),
    ]
