# Generated by Django 6.1.1 on 2026-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classViewApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('ebook', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
