# Generated by Django 6.1.1 on 2026-09-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classViewApp', '0003_book_coverimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverimg',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
