# Generated by Django 6.0.5 on 2026-07-03 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restraurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('cook_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restrauntapp.restaurant')),
            ],
            options={
                'db_table': 'cooks',
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('chef_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restrauntapp.restaurant')),
            ],
            options={
                'db_table': 'chefs',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('waiter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restrauntapp.restaurant')),
            ],
            options={
                'db_table': 'waiters',
            },
        ),
    ]
