# Generated by Django 6.0.5 on 2026-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrauntapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('bio', models.TextField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
