# Generated by Django 6.0.5 on 2026-07-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restrauntapp', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restraurant_id',
            new_name='restaurant_id',
        ),
    ]
